code:
  success: 1
  failure: 0

params_attribute_status:
  required: 0
  optional: 1

per_page: 15

error_codes:
  apartment:
    not_found: 404
    not_used: 400
    used: 400
  client:
    unauthorized: 401
  common:
    bad_request: 400
    connection_refused: 400
    not_found: 404
    server_error: 500
    unauthorized: 400
  customer:
    not_found: 404

response_headers:
  result_code: "result_code"

result_codes:
  failure: "Error"
  success: "Success"

ticket_status:
  active: "active"
  new: "new"
  closed: "closed"
  pending: "pending"
  open: "open"
  spam: "spam"
  trash: "trash"
  out_of_date: "out_of_date"

chungcu: "http://chungcu1.cloudapp.net"
# chungcu: "http://localhost:3000"
